export const ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  IDEMPOTENCY_KEY_INVALID: 'IDEMPOTENCY_KEY_INVALID',

  USER_NOT_FOUND: 'USER_NOT_FOUND',
  STOCK_NOT_FOUND: 'STOCK_NOT_FOUND',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  HOLDING_NOT_FOUND: 'HOLDING_NOT_FOUND',
  RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
  MISSION_NOT_FOUND: 'MISSION_NOT_FOUND',
  CHALLENGE_NOT_FOUND: 'CHALLENGE_NOT_FOUND',
  LEARN_CONTENT_NOT_FOUND: 'LEARN_CONTENT_NOT_FOUND',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  INSUFFICIENT_HOLDING: 'INSUFFICIENT_HOLDING',
  WATCHLIST_ALREADY_EXISTS: 'WATCHLIST_ALREADY_EXISTS',
  WATCHLIST_LIMIT_EXCEEDED: 'WATCHLIST_LIMIT_EXCEEDED',
  WATCHLIST_NOT_FOUND: 'WATCHLIST_NOT_FOUND',

  UPSTREAM_UNAVAILABLE: 'UPSTREAM_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
