/**
 * Canonical API data contracts, shared with the BFF via `@candle/shared`.
 *
 * These are type-only re-exports, so the TypeBox runtime is never bundled into
 * the client. Use them when wiring pages/stores up to the BFF, e.g.:
 *
 *   import type { Quote, Account } from '@/lib/api-types';
 */
export type {
  // market
  Quote,
  Candle,
  CandleInterval,
  StockDetail,
  StockFinancials,
  NewsItem,
  MarketMovers,
  MarketStatus,
  // stock catalog (stock-service)
  StockSummary,
  StockCatalogDetail,
  StockFinancialsInfo,
  StockPage,
  StockSearchQuery,
  StockMarket,
  ListingStatus,
  StockSort,
  // account
  Account,
  AccountStatus,
  AccountBalance,
  Holding,
  HoldingListQuery,
  HoldingSymbolParams,
  Transaction,
  TransactionType,
  TransactionStatus,
  OrderKind,
  PortfolioPoint,
  SectorAllocation,
  OrderCancelResult,
  AmendOrderBody,
  Reservation,
  ReservationTiming,
  ReservationKind,
  ReservationStatus,
  ReservedPosition,
  AccountPositions,
  CreateReservationBody,
  AmendReservationBody,
  WatchlistItem,
  AddWatchlistBody,
  // social
  RankingEntry,
  Mission,
  MissionCategory,
  MissionStatus,
  MissionProgressStatus,
  Challenge,
  ChallengeResult,
  ClaimRewardResult,
  MissionProgressBody,
  LearnContent,
  LearnLevel,
  LearnProgressResult,
  LearnProgressSummary,
  LearnFavoriteResult,
  // user / auth
  UserProfile,
  AuthResponse,
  InvestStyle,
  UpdateProfileBody,
  UserRole,
  UserStatus,
  OAuthProvider,
  ProviderInfo,
  AuthTokens,
  OAuthLoginResult,
  RefreshTokenResult,
  TokenValidateResult,
  NicknameCheckResult,
  MyPageSummary,
  // intraday
  IntradayTick,
  IntradayHistory,
  // notification
  Notification,
  NotificationType,
  NotificationStatus,
  DevicePlatform,
  RegisterDeviceTokenBody,
  RegisterDeviceTokenResult,
  UnreadCountResult,
  // common
  Exchange,
  Currency,
  // websocket
  WsQuoteUpdateData,
  WsQuoteUpdate,
  WsAlertFired,
  WsConnected,
  WsServerMessage,
  WsSubscribe,
  WsUnsubscribe,
  WsClientMessage,
  // chat
  RoomAssignment,
  ChatWireMessage,
  ChatBroadcast,
} from '@candle/shared';
